### ISSUE TITLE
Pumpkins appear when right/left click.

### ISSUE THREAD

**Issue by Terpz710** [IvanCraft623/NetherReactor#1]
So the plugin seemed to run fine at first without the permission but once I add the activation permission the pumpkins starts to appear like a bunch.

**Comment by IvanCraft623** [comment]
I don't get it, could you send a video?

**Comment by Terpz710** [comment]
Sorry it’s a bug with customies. theres a bug that if you break/place blocks there’s a chance that it will change the block data. It’s client side tho and will go away after relogging.

**Comment by n00bslayr94** [comment]
I see you say its an issue with customies but I dont actually understand how you use it without the pumpkins appearing though!? They're everywhere. how do you activate it ???
![image](https://github.com/IvanCraft623/NetherReactor/assets/132199379/dc40886d-7485-4cc5-b781-2f9ed34d8943) 
![image](https://github.com/IvanCraft623/NetherReactor/assets/132199379/7fc370ff-1a16-4ad0-9c7d-e4857538afb6)

**Comment by IvanCraft623** [comment]
Most likely it's some plugin messing with block mappings

**Comment by IvanCraft623** [comment]
@n00bslayr94 Please if you want this fixed, contact me on discord (@IvanCraft623), because the information they give to reproduce the bug is vague and I am not able to reproduce it.

**Comment by skyss0fly-pm-pl** [comment]
> @n00bslayr94 Please if you want this fixed, contact me on discord (@IvanCraft623), because the information they give to reproduce the bug is vague and I am not able to reproduce it.

Its reproduced using Customies latest Version as of this Time and Your NetherReactor Plugin. You place a bedrock block and right click it turns to pumpkin and then right click that and 5 more appear and so on

**Comment by IvanCraft623** [comment]
@skyss0fly-pm-pl if also you are having the problema, please provide a list of plugins that You are using, and try ti reproduce the issue without other plugins

**Comment by IvanCraft623** [comment]
@skyss0fly-pm-pl if also you are having the problema, please provide a list of plugins that You are using, and try ti reproduce the issue without other plugins

**Comment by n00bslayr94** [comment]
https://github.com/diamond-gold/DummyItemsBlocks/issues/18#issue-2094812954
